# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: goreleaser

on:
  push:
    tags:
      - v*.*.*

permissions:
  contents: write
  packages: write
  id-token: write

concurrency:
  group: goreleaser
  cancel-in-progress: true

jobs:
  release:
    if: ${{ !contains(github.repository, '-internal') }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      id-token: write
    env:
      DOCKER_CLI_EXPERIMENTAL: enabled
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          lfs: false

      - run: |
          git config --global url."https://${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/charmbracelet".insteadOf "https://github.com/charmbracelet"
          git config --global url."https://${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/charmcli".insteadOf "https://github.com/charmcli"

      - uses: actions/setup-go@v6
        with:
          go-version: "1.26"
          cache: true
          check-latest: true

      - uses: sigstore/cosign-installer@ba7bc0a3fef59531c69a25acd34668d6d3fe6f22 # v4.1.0

      - uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - run: nix profile install nixpkgs#nixfmt-rfc-style

      - uses: anchore/sbom-action/download-syft@v0.23.1

      - uses: docker/setup-qemu-action@v4

      - uses: docker/setup-buildx-action@v4

      - uses: docker/login-action@v4
        name: ghcr.io login
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/login-action@v4
        name: docker.io login
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - run: |
          echo "$NFPM_GPG_KEY" > ${{ runner.temp }}/gpg.key
        env:
          NFPM_GPG_KEY: ${{ secrets.NFPM_GPG_KEY }}

      - uses: actions/setup-node@v6
        with:
          node-version: "24"
          registry-url: "https://registry.npmjs.org"

      - uses: samuelmeuli/action-snapcraft@v3

      - uses: goreleaser/goreleaser-action@v7
        with:
          version: nightly
          distribution: goreleaser-pro
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HOMEBREW_TAP_GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          GORELEASER_KEY: ${{ secrets.GORELEASER_KEY }}
          AUR_KEY: ${{ secrets.AUR_KEY }}
          FURY_TOKEN: ${{ secrets.FURY_TOKEN }}
          GPG_KEY_PATH: ${{ runner.temp }}/gpg.key
          NFPM_DEFAULT_PASSPHRASE: ${{ secrets.NFPM_PASSPHRASE }}
          TWITTER_CONSUMER_KEY: ${{ secrets.TWITTER_CONSUMER_KEY }}
          TWITTER_CONSUMER_SECRET: ${{ secrets.TWITTER_CONSUMER_SECRET }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
          MASTODON_CLIENT_ID: ${{ secrets.MASTODON_CLIENT_ID }}
          MASTODON_CLIENT_SECRET: ${{ secrets.MASTODON_CLIENT_SECRET }}
          MASTODON_ACCESS_TOKEN: ${{ secrets.MASTODON_ACCESS_TOKEN }}
          DISCORD_WEBHOOK_ID: ${{ secrets.DISCORD_WEBHOOK_ID }}
          DISCORD_WEBHOOK_TOKEN: ${{ secrets.DISCORD_WEBHOOK_TOKEN }}
          MACOS_SIGN_P12: ${{ secrets.MACOS_SIGN_P12 }}
          MACOS_SIGN_PASSWORD: ${{ secrets.MACOS_SIGN_PASSWORD }}
          MACOS_SIGN_ENTITLEMENTS: ./.github/entitlements.plist
          MACOS_NOTARY_ISSUER_ID: ${{ secrets.MACOS_NOTARY_ISSUER_ID }}
          MACOS_NOTARY_KEY_ID: ${{ secrets.MACOS_NOTARY_KEY_ID }}
          MACOS_NOTARY_KEY: ${{ secrets.MACOS_NOTARY_KEY }}
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPCRAFT_TOKEN }}
          POSTHOG_KEY: ${{ secrets.POSTHOG_KEY }}

      - uses: actions/upload-artifact@v7
        if: ${{ always() }}
        with:
          retention-days: 30
          name: dist
          path: |
            dist
